name: Publish release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version information
        id: vars
        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.version }}
          tag_name: ${{ steps.vars.outputs.version }}
          body: ${{ github.event.head_commit.message }}
          draft: false